import type { CreditItem } from '../types/credit';

export const mockData: CreditItem[] = [
  {
    id: '1', idBanner: '12345', nombres: 'Juan', apellidos: 'Pérez', carrera: 'Ingeniería', identificacion: '987654321', periodo: '2024-1', matricula: '0001', entrada: '01/01/2024', cuotas: '5', fechaCreacion: '01/01/2024', estado: 'Pendiente', prefactura: 'Verificar', rolPagos: 'Verificar', pago: 'Verificar', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '2', idBanner: '12346', nombres: 'Ana', apellidos: 'Gómez', carrera: 'Arquitectura', identificacion: '123456789', periodo: '2024-1', matricula: '0002', entrada: '02/01/2024', cuotas: '4', fechaCreacion: '02/01/2024', estado: 'Aprobado', prefactura: 'Emitida', rolPagos: 'Pagado', pago: 'Completo', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '3', idBanner: '12347', nombres: 'Carlos', apellidos: 'Martínez', carrera: 'Medicina', identificacion: '234567890', periodo: '2024-2', matricula: '0003', entrada: '03/01/2024', cuotas: '6', fechaCreacion: '03/01/2024', estado: 'Pendiente', prefactura: 'Verificar', rolPagos: 'Verificar', pago: 'Pendiente', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '4', idBanner: '12348', nombres: 'Laura', apellidos: 'Torres', carrera: 'Derecho', identificacion: '345678901', periodo: '2024-2', matricula: '0004', entrada: '04/01/2024', cuotas: '3', fechaCreacion: '04/01/2024', estado: 'Aprobado', prefactura: 'Emitida', rolPagos: 'Pagado', pago: 'Completo', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '5', idBanner: '12349', nombres: 'Pedro', apellidos: 'Jiménez', carrera: 'Economía', identificacion: '456789012', periodo: '2024-3', matricula: '0005', entrada: '05/01/2024', cuotas: '5', fechaCreacion: '05/01/2024', estado: 'Pendiente', prefactura: 'Verificar', rolPagos: 'Verificar', pago: 'Pendiente', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '6', idBanner: '12350', nombres: 'Sofia', apellidos: 'Ramírez', carrera: 'Biología', identificacion: '567890123', periodo: '2024-3', matricula: '0006', entrada: '06/01/2024', cuotas: '4', fechaCreacion: '06/01/2024', estado: 'Aprobado', prefactura: 'Emitida', rolPagos: 'Pagado', pago: 'Completo', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '7', idBanner: '12351', nombres: 'Marta', apellidos: 'Sánchez', carrera: 'Historia', identificacion: '678901234', periodo: '2024-4', matricula: '0007', entrada: '07/01/2024', cuotas: '6', fechaCreacion: '07/01/2024', estado: 'Pendiente', prefactura: 'Verificar', rolPagos: 'Verificar', pago: 'Pendiente', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '8', idBanner: '12352', nombres: 'Javier', apellidos: 'Castro', carrera: 'Química', identificacion: '789012345', periodo: '2024-4', matricula: '0008', entrada: '08/01/2024', cuotas: '5', fechaCreacion: '08/01/2024', estado: 'Aprobado', prefactura: 'Emitida', rolPagos: 'Pagado', pago: 'Completo', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '9', idBanner: '12353', nombres: 'Daniela', apellidos: 'Morales', carrera: 'Sociología', identificacion: '890123456', periodo: '2024-5', matricula: '0009', entrada: '09/01/2024', cuotas: '4', fechaCreacion: '09/01/2024', estado: 'Pendiente', prefactura: 'Verificar', rolPagos: 'Verificar', pago: 'Pendiente', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '10', idBanner: '12354', nombres: 'Ricardo', apellidos: 'Vásquez', carrera: 'Filosofía', identificacion: '901234567', periodo: '2024-5', matricula: '0010', entrada: '10/01/2024', cuotas: '5', fechaCreacion: '10/01/2024', estado: 'Aprobado', prefactura: 'Emitida', rolPagos: 'Pagado', pago: 'Completo', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '11', idBanner: '12355', nombres: 'Elena', apellidos: 'García', carrera: 'Antropología', identificacion: '012345678', periodo: '2024-6', matricula: '0011', entrada: '11/01/2024', cuotas: '3', fechaCreacion: '11/01/2024', estado: 'Pendiente', prefactura: 'Verificar', rolPagos: 'Verificar', pago: 'Pendiente', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '12', idBanner: '12356', nombres: 'José', apellidos: 'Hernández', carrera: 'Ingeniería Civil', identificacion: '123456780', periodo: '2024-6', matricula: '0012', entrada: '12/01/2024', cuotas: '5', fechaCreacion: '12/01/2024', estado: 'Aprobado', prefactura: 'Emitida', rolPagos: 'Pagado', pago: 'Completo', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '13', idBanner: '12357', nombres: 'Catalina', apellidos: 'Ortiz', carrera: 'Publicidad', identificacion: '234567890', periodo: '2024-7', matricula: '0013', entrada: '13/01/2024', cuotas: '4', fechaCreacion: '13/01/2024', estado: 'Pendiente', prefactura: 'Verificar', rolPagos: 'Verificar', pago: 'Pendiente', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '14', idBanner: '12358', nombres: 'Samuel', apellidos: 'Cruz', carrera: 'Relaciones Internacionales', identificacion: '345678901', periodo: '2024-7', matricula: '0014', entrada: '14/01/2024', cuotas: '5', fechaCreacion: '14/01/2024', estado: 'Aprobado', prefactura: 'Emitida', rolPagos: 'Pagado', pago: 'Completo', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
  { id: '15', idBanner: '12359', nombres: 'Paola', apellidos: 'Ríos', carrera: 'Literatura', identificacion: '456789012', periodo: '2024-8', matricula: '0015', entrada: '15/01/2024', cuotas: '3', fechaCreacion: '15/01/2024', estado: 'Pendiente', prefactura: 'Verificar', rolPagos: 'Verificar', pago: 'Pendiente', ultimaModificacion: 'Admin',
    acciones: { aceptar: () => console.log('Aceptar'), rechazar: () => console.log('Rechazar'), enviarBanner: () => console.log('Enviar a Banner') },
    solicitud: () => console.log('Descargar'),
  },
];
